services:

  db:
    image: mariadb:11
    container_name: mariadb
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - wp-network

  wordpress:
    image: wordpress:php8.2-fpm-alpine
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - wp-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TRUSTED_IP=${TRUSTED_IP}
      - SERVER_NAME=${SERVER_NAME}
    volumes:
      - ./nginx/conf.d/wordpress.conf:/etc/nginx/templates/wordpress.conf.template:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./wordpress:/var/www/html:ro 
    depends_on:
      - wordpress
    restart: unless-stopped
    networks:
      - wp-network

  # Автоматичне оновлення SSL
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
      - SERVERURL=${SERVER_NAME}
      - SERVERPORT=51820
      - PEERS=1 
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0 
      - ALLOWEDIPS=0.0.0.0/0 
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules 
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - wp-network

volumes:
  db_data:

networks:
  wp-network:
    ipam:
      config:
        - subnet: 172.25.0.0/24

